# permalink: /:title.html
encoding: utf-8


title: 나물코드 블로그
url: http://namulcode.com
feed: /atom.xml
description: d__
comment: c__

author: 
    name: donghyuc-kim
    email: inbox@soopul.com

css: 
  - /res/font.css
  - /res/form.css
  - /res/common.css

js: 
  - /res/addLoad.js


plugins: [jekyll-paginate] 

paginate: 5
patinate_path: /page:num